export const SET_PERSONNEL_DATA = 'SET_PERSONNEL_DATA';
export const GET_PERSONNEL_DATA = 'GET_PERSONNEL_DATA';
export const SET_NEW_STATUS = 'SET_NEW_STATUS';

export const SET_FILTER_OPERATION = 'SET_FILTER_OPERATION';
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';

export const SET_STATE_FROM_LOCAL_STORAGE = 'SET_STATE_FROM_LOCAL_STORAGE';
